use std::collections::HashMap;
use std::env;
use std::fs;
use std::io::{self, Write};

#[derive(Debug, Clone, PartialEq)]
enum Token { Fn, Let, If, Else, While, Return, True, False, Ident(String), Int(i64), Str(String), Plus, Minus, Star, Slash, Eq, EqEq, BangEq, Lt, Lte, Gt, Gte, LParen, RParen, LBrace, RBrace, Comma, Colon, Arrow, Semi, Eof }

fn lex(src: &str) -> Result<Vec<Token>, String> {
    let chars: Vec<char> = src.chars().collect(); let mut i=0; let mut out=Vec::new();
    while i<chars.len() { let c=chars[i];
        if c.is_whitespace() { i+=1; continue }
        if c=='#' { while i<chars.len() && chars[i]!='\n' { i+=1 } continue }
        if c.is_ascii_digit() { let s=i; while i<chars.len()&&chars[i].is_ascii_digit(){i+=1}; out.push(Token::Int(src.chars().skip(s).take(i-s).collect::<String>().parse().unwrap())); continue }
        if c.is_ascii_alphabetic()||c=='_' { let s=i; while i<chars.len()&&(chars[i].is_ascii_alphanumeric()||chars[i]=='_'){i+=1}; let w: String=chars[s..i].iter().collect(); out.push(match w.as_str(){"fn"=>Token::Fn,"let"=>Token::Let,"if"=>Token::If,"else"=>Token::Else,"while"=>Token::While,"return"=>Token::Return,"true"=>Token::True,"false"=>Token::False,_=>Token::Ident(w)}); continue }
        if c=='"' { i+=1; let s=i; while i<chars.len()&&chars[i]!='"'{i+=1}; if i==chars.len(){return Err("unterminated string".into())}; out.push(Token::Str(chars[s..i].iter().collect())); i+=1; continue }
        let t=match c {'+'=>Token::Plus,'-'=>{if i+1<chars.len()&&chars[i+1]=='>'{i+=1;Token::Arrow}else{Token::Minus}},'*'=>Token::Star,'/'=>Token::Slash,'('=>Token::LParen,')'=>Token::RParen,'{'=>Token::LBrace,'}'=>Token::RBrace,','=>Token::Comma,':'=>Token::Colon,';'=>Token::Semi,'='=>{if i+1<chars.len()&&chars[i+1]=='='{i+=1;Token::EqEq}else{Token::Eq}},'!'=>{if i+1<chars.len()&&chars[i+1]=='=' {i+=1;Token::BangEq}else{return Err("unexpected !".into())}},'<'=>{if i+1<chars.len()&&chars[i+1]=='='{i+=1;Token::Lte}else{Token::Lt}},'>'=>{if i+1<chars.len()&&chars[i+1]=='='{i+=1;Token::Gte}else{Token::Gt}},_=>return Err(format!("unexpected character: {c}"))}; out.push(t); i+=1;
    } out.push(Token::Eof); Ok(out)
}

#[derive(Debug, Clone)] enum Expr { Int(i64), Str(String), Bool(bool), Var(String), Binary(Box<Expr>,Token,Box<Expr>), Call(String,Vec<Expr>) }
#[derive(Debug, Clone)] enum Stmt { Let(String,Expr), Assign(String,Expr), Expr(Expr), Return(Expr), If(Expr,Vec<Stmt>,Vec<Stmt>), While(Expr,Vec<Stmt>) }
#[derive(Debug, Clone)] struct Function { name:String, params:Vec<String>, body:Vec<Stmt> }

struct Parser { t:Vec<Token>, p:usize }
impl Parser { fn new(t:Vec<Token>)->Self{Self{t,p:0}} fn cur(&self)->&Token{&self.t[self.p]} fn bump(&mut self)->Token{let x=self.t[self.p].clone();self.p+=1;x} fn eat(&mut self,w:Token)->Result<(),String>{if *self.cur()==w{self.bump();Ok(())}else{Err(format!("expected {:?}, got {:?}",w,self.cur()))}}
 fn program(&mut self)->Result<Vec<Function>,String>{let mut f=Vec::new();while *self.cur()!=Token::Eof{f.push(self.function()?)}Ok(f)}
 fn function(&mut self)->Result<Function,String>{self.eat(Token::Fn)?;let name=match self.bump(){Token::Ident(x)=>x,_=>return Err("expected function name".into())};self.eat(Token::LParen)?;let mut ps=Vec::new();if *self.cur()!=Token::RParen{loop{match self.bump(){Token::Ident(x)=>ps.push(x),_=>return Err("expected parameter".into())};if *self.cur()==Token::Colon{self.bump();self.bump();}if *self.cur()==Token::Comma{self.bump();}else{break}}}self.eat(Token::RParen)?;if *self.cur()==Token::Arrow{self.bump();self.bump();}self.eat(Token::LBrace)?;let body=self.block()?;Ok(Function{name,params:ps,body})}
 fn block(&mut self)->Result<Vec<Stmt>,String>{let mut v=Vec::new();while *self.cur()!=Token::RBrace&&*self.cur()!=Token::Eof{v.push(self.stmt()?);if *self.cur()==Token::Semi{self.bump();}}self.eat(Token::RBrace)?;Ok(v)}
 fn stmt(&mut self)->Result<Stmt,String>{match self.cur(){Token::Let=>{self.bump();self.let_stmt()},Token::If=>self.if_stmt(),Token::While=>self.while_stmt(),Token::Return=>{self.bump();Ok(Stmt::Return(self.expr()?))},Token::Ident(_)=>{if let Token::Ident(n)=self.t[self.p].clone(){if self.t.get(self.p+1)==Some(&Token::Eq){self.bump();self.bump();return Ok(Stmt::Assign(n,self.expr()?))}}Ok(Stmt::Expr(self.expr()?))},_=>Ok(Stmt::Expr(self.expr()?))}}
 fn let_stmt(&mut self)->Result<Stmt,String>{let n=match self.bump(){Token::Ident(x)=>x,_=>return Err("expected variable name".into())};if *self.cur()==Token::Colon{self.bump();self.bump();}if *self.cur()==Token::Eq{self.bump();}Ok(Stmt::Let(n,self.expr()?))}
 fn if_stmt(&mut self)->Result<Stmt,String>{self.bump();let c=self.expr()?;self.eat(Token::LBrace)?;let a=self.block()?;let b=if *self.cur()==Token::Else{self.bump();self.eat(Token::LBrace)?;self.block()?}else{Vec::new()};Ok(Stmt::If(c,a,b))}
 fn while_stmt(&mut self)->Result<Stmt,String>{self.bump();let c=self.expr()?;self.eat(Token::LBrace)?;Ok(Stmt::While(c,self.block()?))}
 fn expr(&mut self)->Result<Expr,String>{self.compare()}
 fn compare(&mut self)->Result<Expr,String>{let mut x=self.add()?;while matches!(self.cur(),Token::EqEq|Token::BangEq|Token::Lt|Token::Lte|Token::Gt|Token::Gte){let op=self.bump();x=Expr::Binary(Box::new(x),op,Box::new(self.add()?))}Ok(x)}
 fn add(&mut self)->Result<Expr,String>{let mut x=self.mul()?;while matches!(self.cur(),Token::Plus|Token::Minus){let op=self.bump();x=Expr::Binary(Box::new(x),op,Box::new(self.mul()?))}Ok(x)}
 fn mul(&mut self)->Result<Expr,String>{let mut x=self.atom()?;while matches!(self.cur(),Token::Star|Token::Slash){let op=self.bump();x=Expr::Binary(Box::new(x),op,Box::new(self.atom()?))}Ok(x)}
 fn atom(&mut self)->Result<Expr,String>{match self.bump(){Token::Int(x)=>Ok(Expr::Int(x)),Token::Str(x)=>Ok(Expr::Str(x)),Token::True=>Ok(Expr::Bool(true)),Token::False=>Ok(Expr::Bool(false)),Token::Ident(n)=>{if *self.cur()==Token::LParen{self.bump();let mut a=Vec::new();if *self.cur()!=Token::RParen{loop{a.push(self.expr()?);if *self.cur()==Token::Comma{self.bump();}else{break}}}self.eat(Token::RParen)?;Ok(Expr::Call(n,a))}else{Ok(Expr::Var(n))}},Token::LParen=>{let x=self.expr()?;self.eat(Token::RParen)?;Ok(x)},x=>Err(format!("unexpected token {:?}",x))}}
}

#[derive(Debug,Clone,PartialEq)] enum Value { Int(i64), Str(String), Bool(bool), Unit }
struct Vm { funcs:HashMap<String,Function> }
impl Vm { fn run(&self)->Result<Value,String>{self.call("main",vec![])} fn call(&self,n:&str,args:Vec<Value>)->Result<Value,String>{if n=="print"{for x in args{println!("{}",show(&x))}return Ok(Value::Unit)}let f=self.funcs.get(n).ok_or_else(||format!("unknown function `{n}`"))?;let mut e=HashMap::new();for(i,p)in f.params.iter().enumerate(){e.insert(p.clone(),args.get(i).cloned().unwrap_or(Value::Unit));}match exec(&f.body,&mut e,self)?{Some(v)=>Ok(v),None=>Ok(Value::Unit)}}}
fn show(v:&Value)->String{match v{Value::Int(x)=>x.to_string(),Value::Str(x)=>x.clone(),Value::Bool(x)=>x.to_string(),Value::Unit=>"unit".into()}}
fn truth(v:&Value)->bool{matches!(v,Value::Bool(true))||matches!(v,Value::Int(x)if *x!=0)}
fn val(x:&Expr,e:&mut HashMap<String,Value>,vm:&Vm)->Result<Value,String>{match x{Expr::Int(x)=>Ok(Value::Int(*x)),Expr::Str(x)=>Ok(Value::Str(x.clone())),Expr::Bool(x)=>Ok(Value::Bool(*x)),Expr::Var(n)=>e.get(n).cloned().ok_or_else(||format!("undefined variable `{n}`")),Expr::Call(n,a)=>{let z=a.iter().map(|x|val(x,e,vm)).collect::<Result<Vec<_>,_>>()?;vm.call(n,z)},Expr::Binary(a,o,b)=>{let x=val(a,e,vm)?;let y=val(b,e,vm)?;bin(x,o,y)}}}
fn bin(a:Value,o:&Token,b:Value)->Result<Value,String>{match (a,b,o){(Value::Int(x),Value::Int(y),Token::Plus)=>Ok(Value::Int(x+y)),(Value::Int(x),Value::Int(y),Token::Minus)=>Ok(Value::Int(x-y)),(Value::Int(x),Value::Int(y),Token::Star)=>Ok(Value::Int(x*y)),(Value::Int(x),Value::Int(y),Token::Slash)=>Ok(Value::Int(x/y)),(Value::Int(x),Value::Int(y),Token::EqEq)=>Ok(Value::Bool(x==y)),(Value::Int(x),Value::Int(y),Token::BangEq)=>Ok(Value::Bool(x!=y)),(Value::Int(x),Value::Int(y),Token::Lt)=>Ok(Value::Bool(x<y)),(Value::Int(x),Value::Int(y),Token::Lte)=>Ok(Value::Bool(x<=y)),(Value::Int(x),Value::Int(y),Token::Gt)=>Ok(Value::Bool(x>y)),(Value::Int(x),Value::Int(y),Token::Gte)=>Ok(Value::Bool(x>=y)),(Value::Str(x),Value::Str(y),Token::Plus)=>Ok(Value::Str(x+&y)),(x,y,Token::EqEq)=>Ok(Value::Bool(x==y)),(x,y,Token::BangEq)=>Ok(Value::Bool(x!=y)),_=>Err("invalid operands".into())}}
fn exec(xs:&[Stmt],e:&mut HashMap<String,Value>,vm:&Vm)->Result<Option<Value>,String>{for s in xs{match s{Stmt::Let(n,x)|Stmt::Assign(n,x)=>{let value=val(x,e,vm)?;e.insert(n.clone(),value);},Stmt::Expr(x)=>{val(x,e,vm)?;},Stmt::Return(x)=>return Ok(Some(val(x,e,vm)?)),Stmt::If(c,a,b)=>{if truth(&val(c,e,vm)?){if let Some(v)=exec(a,e,vm)?{return Ok(Some(v))}}else if let Some(v)=exec(b,e,vm)?{return Ok(Some(v))}},Stmt::While(c,b)=>{while truth(&val(c,e,vm)?){if let Some(v)=exec(b,e,vm)?{return Ok(Some(v))}}}}}Ok(None)}
fn check_program(fs:&[Function])->Result<(),String>{let mut names=HashMap::new();for f in fs{if names.insert(f.name.clone(),()).is_some(){return Err(format!("duplicate function `{}`",f.name))}}if !names.contains_key("main"){return Err("program must define fn main()".into())}for f in fs{check_stmts(&f.body,&names)?;}Ok(())}
fn check_stmts(xs:&[Stmt],names:&HashMap<String,()>)->Result<(),String>{for s in xs{match s{Stmt::Expr(x)|Stmt::Let(_,x)|Stmt::Assign(_,x)|Stmt::Return(x)=>check_expr(x,names)?,Stmt::If(c,a,b)=>{check_expr(c,names)?;check_stmts(a,names)?;check_stmts(b,names)?},Stmt::While(c,b)=>{check_expr(c,names)?;check_stmts(b,names)?}}}Ok(())}
fn check_expr(x:&Expr,names:&HashMap<String,()>)->Result<(),String>{match x{Expr::Binary(a,_,b)=>{check_expr(a,names)?;check_expr(b,names)?},Expr::Call(n,a)=>{if n!="print"&&!names.contains_key(n){return Err(format!("unknown function `{n}`"))}for x in a{check_expr(x,names)?}},_=>{}}Ok(())}
fn execute(src:&str)->Result<Value,String>{let toks=lex(src)?;let mut p=Parser::new(toks);let fs=p.program()?;check_program(&fs)?;let map=fs.into_iter().map(|f|(f.name.clone(),f)).collect();Vm{funcs:map}.run()}
fn main(){let a:Vec<String>=env::args().collect();if a.len()<2{eprintln!("S+N++ v0.1 — usage: snp run <file.snp> | snp check <file.snp> | snp repl");return}if a[1]=="repl"{let mut line=String::new();loop{print!("snp> ");io::stdout().flush().unwrap();line.clear();if io::stdin().read_line(&mut line).unwrap()==0{break}let src=format!("fn main() {{{}}}",line);match execute(&src){Ok(v)=>if v!=Value::Unit{println!("{}",show(&v))},Err(e)=>eprintln!("error: {e}")}}return}if a.len()<3{eprintln!("missing file");return}let src=match fs::read_to_string(&a[2]){Ok(x)=>x,Err(e)=>{eprintln!("cannot read file: {e}");return}};match execute(&src){Ok(v)=>{if a[1]=="check"{println!("ok: valid S+N++ program")}else if v!=Value::Unit{println!("program returned {}",show(&v))}},Err(e)=>eprintln!("error: {e}")}}

#[cfg(test)] mod tests {use super::*;#[test]fn arithmetic(){let s="fn main(){ print(2+3*4); return 0; }";assert_eq!(execute(s),Ok(Value::Int(0)));}#[test]fn function_call(){let s="fn add(a:Int,b:Int){return a+b;} fn main(){return add(2,3);}";assert_eq!(execute(s),Ok(Value::Int(5)));}#[test]fn unknown_function_is_diagnostic(){let s="fn main(){missing();}";assert!(execute(s).unwrap_err().contains("unknown function"));}}
