use std::collections::HashMap;
use std::env;
use std::fs;
use std::io::{self, Write};
use std::sync::{Mutex, OnceLock, atomic::{AtomicUsize, Ordering}};
use std::thread::{self, JoinHandle};
use std::collections::HashMap as Map;

static THREADS: OnceLock<Mutex<Map<usize, JoinHandle<Value>>>> = OnceLock::new();
static NEXT_THREAD_ID: AtomicUsize = AtomicUsize::new(1);
fn thread_table() -> &'static Mutex<Map<usize, JoinHandle<Value>>> { THREADS.get_or_init(|| Mutex::new(Map::new())) }


#[derive(Debug, Clone, PartialEq)]
enum Token { Fn, Let, If, Else, While, Return, True, False, Mut, Ident(String), Int(i64), Str(String), Amp, Plus, Minus, Star, Slash, Eq, EqEq, BangEq, Lt, Lte, Gt, Gte, LParen, RParen, LBrace, RBrace, Comma, Colon, Arrow, Semi, Eof }

fn lex(src: &str) -> Result<Vec<Token>, String> {
    let chars: Vec<char> = src.chars().collect(); let mut i=0; let mut out=Vec::new();
    while i<chars.len() { let c=chars[i];
        if c.is_whitespace() { i+=1; continue }
        if c=='#' { while i<chars.len() && chars[i]!='\n' { i+=1 } continue }
        if c.is_ascii_digit() { let s=i; while i<chars.len()&&chars[i].is_ascii_digit(){i+=1}; out.push(Token::Int(src.chars().skip(s).take(i-s).collect::<String>().parse().unwrap())); continue }
        if c.is_ascii_alphabetic()||c=='_' { let s=i; while i<chars.len()&&(chars[i].is_ascii_alphanumeric()||chars[i]=='_'){i+=1}; let w: String=chars[s..i].iter().collect(); out.push(match w.as_str(){"fn"=>Token::Fn,"let"=>Token::Let,"if"=>Token::If,"else"=>Token::Else,"while"=>Token::While,"return"=>Token::Return,"true"=>Token::True,"false"=>Token::False,"mut"=>Token::Mut,_=>Token::Ident(w)}); continue }
        if c=='"' { i+=1; let s=i; while i<chars.len()&&chars[i]!='"'{i+=1}; if i==chars.len(){return Err("unterminated string".into())}; out.push(Token::Str(chars[s..i].iter().collect())); i+=1; continue }
        let t=match c {'&'=>Token::Amp,'+'=>Token::Plus,'-'=>{if i+1<chars.len()&&chars[i+1]=='>'{i+=1;Token::Arrow}else{Token::Minus}},'*'=>Token::Star,'/'=>Token::Slash,'('=>Token::LParen,')'=>Token::RParen,'{'=>Token::LBrace,'}'=>Token::RBrace,','=>Token::Comma,':'=>Token::Colon,';'=>Token::Semi,'='=>{if i+1<chars.len()&&chars[i+1]=='='{i+=1;Token::EqEq}else{Token::Eq}},'!'=>{if i+1<chars.len()&&chars[i+1]=='=' {i+=1;Token::BangEq}else{return Err("unexpected !".into())}},'<'=>{if i+1<chars.len()&&chars[i+1]=='='{i+=1;Token::Lte}else{Token::Lt}},'>'=>{if i+1<chars.len()&&chars[i+1]=='='{i+=1;Token::Gte}else{Token::Gt}},_=>return Err(format!("unexpected character: {c}"))}; out.push(t); i+=1;
    } out.push(Token::Eof); Ok(out)
}

#[derive(Debug, Clone, PartialEq)] enum Type { Int, Str, Bool, Unit, Ref(Box<Type>), MutRef(Box<Type>), Unknown }
#[derive(Debug, Clone)] enum Expr { Int(i64), Str(String), Bool(bool), Var(String), Binary(Box<Expr>,Token,Box<Expr>), Call(String,Vec<Expr>) }
#[derive(Debug, Clone)] enum Stmt { Let(String,Expr), Decl(String,Type), Assign(String,Expr), Expr(Expr), Return(Expr), If(Expr,Vec<Stmt>,Vec<Stmt>), While(Expr,Vec<Stmt>) }
#[derive(Debug, Clone)] struct Function { name:String, params:Vec<String>, param_types:Vec<Type>, return_type:Type, body:Vec<Stmt> }

struct Parser { t:Vec<Token>, p:usize }
impl Parser { fn new(t:Vec<Token>)->Self{Self{t,p:0}} fn cur(&self)->&Token{&self.t[self.p]} fn bump(&mut self)->Token{let x=self.t[self.p].clone();self.p+=1;x} fn eat(&mut self,w:Token)->Result<(),String>{if *self.cur()==w{self.bump();Ok(())}else{Err(format!("expected {:?}, got {:?}",w,self.cur()))}}
 fn program(&mut self)->Result<Vec<Function>,String>{let mut f=Vec::new();while *self.cur()!=Token::Eof{f.push(self.function()?)}Ok(f)}
 fn parse_type(&mut self)->Result<Type,String>{if *self.cur()==Token::Amp{self.bump();if *self.cur()==Token::Mut{self.bump();return Ok(Type::MutRef(Box::new(self.parse_type()?)))}return Ok(Type::Ref(Box::new(self.parse_type()?)))}match self.bump(){Token::Ident(x)=>match x.as_str(){"Int"=>Ok(Type::Int),"String"=>Ok(Type::Str),"Bool"=>Ok(Type::Bool),"Unit"=>Ok(Type::Unit),_=>Err(format!("unknown type `{x}`"))},x=>Err(format!("expected type, got {:?}",x))}}
 fn function(&mut self)->Result<Function,String>{self.eat(Token::Fn)?;let name=match self.bump(){Token::Ident(x)=>x,_=>return Err("expected function name".into())};self.eat(Token::LParen)?;let mut ps=Vec::new();let mut pts=Vec::new();if *self.cur()!=Token::RParen{loop{match self.bump(){Token::Ident(x)=>ps.push(x),_=>return Err("expected parameter".into())};self.eat(Token::Colon)?;pts.push(self.parse_type()?);if *self.cur()==Token::Comma{self.bump();}else{break}}}self.eat(Token::RParen)?;let rt=if *self.cur()==Token::Arrow{self.bump();self.parse_type()?}else{Type::Unit};self.eat(Token::LBrace)?;let body=self.block()?;Ok(Function{name,params:ps,param_types:pts,return_type:rt,body})}
 fn block(&mut self)->Result<Vec<Stmt>,String>{let mut v=Vec::new();while *self.cur()!=Token::RBrace&&*self.cur()!=Token::Eof{v.push(self.stmt()?);if *self.cur()==Token::Semi{self.bump();}}self.eat(Token::RBrace)?;Ok(v)}
 fn stmt(&mut self)->Result<Stmt,String>{match self.cur(){Token::Let=>{self.bump();self.let_stmt()},Token::If=>self.if_stmt(),Token::While=>self.while_stmt(),Token::Return=>{self.bump();Ok(Stmt::Return(self.expr()?))},Token::Ident(_)=>{if let Token::Ident(n)=self.t[self.p].clone(){if self.t.get(self.p+1)==Some(&Token::Eq){self.bump();self.bump();return Ok(Stmt::Assign(n,self.expr()?))}}Ok(Stmt::Expr(self.expr()?))},_=>Ok(Stmt::Expr(self.expr()?))}}
 fn let_stmt(&mut self)->Result<Stmt,String>{let n=match self.bump(){Token::Ident(x)=>x,_=>return Err("expected variable name".into())};let declared=if *self.cur()==Token::Colon{self.bump();Some(self.parse_type()?)}else{None};if *self.cur()!=Token::Eq{if let Some(t)=declared{return Ok(Stmt::Decl(n,t))}return Err("let requires an initializer or explicit type".into())}self.bump();Ok(Stmt::Let(n,self.expr()?))}
 fn if_stmt(&mut self)->Result<Stmt,String>{self.bump();let c=self.expr()?;self.eat(Token::LBrace)?;let a=self.block()?;let b=if *self.cur()==Token::Else{self.bump();self.eat(Token::LBrace)?;self.block()?}else{Vec::new()};Ok(Stmt::If(c,a,b))}
 fn while_stmt(&mut self)->Result<Stmt,String>{self.bump();let c=self.expr()?;self.eat(Token::LBrace)?;Ok(Stmt::While(c,self.block()?))}
 fn expr(&mut self)->Result<Expr,String>{self.compare()}
 fn compare(&mut self)->Result<Expr,String>{let mut x=self.add()?;while matches!(self.cur(),Token::EqEq|Token::BangEq|Token::Lt|Token::Lte|Token::Gt|Token::Gte){let op=self.bump();x=Expr::Binary(Box::new(x),op,Box::new(self.add()?))}Ok(x)}
 fn add(&mut self)->Result<Expr,String>{let mut x=self.mul()?;while matches!(self.cur(),Token::Plus|Token::Minus){let op=self.bump();x=Expr::Binary(Box::new(x),op,Box::new(self.mul()?))}Ok(x)}
 fn mul(&mut self)->Result<Expr,String>{let mut x=self.atom()?;while matches!(self.cur(),Token::Star|Token::Slash){let op=self.bump();x=Expr::Binary(Box::new(x),op,Box::new(self.atom()?))}Ok(x)}
 fn atom(&mut self)->Result<Expr,String>{match self.bump(){Token::Int(x)=>Ok(Expr::Int(x)),Token::Str(x)=>Ok(Expr::Str(x)),Token::True=>Ok(Expr::Bool(true)),Token::False=>Ok(Expr::Bool(false)),Token::Ident(n)=>{if *self.cur()==Token::LParen{self.bump();let mut a=Vec::new();if *self.cur()!=Token::RParen{loop{a.push(self.expr()?);if *self.cur()==Token::Comma{self.bump();}else{break}}}self.eat(Token::RParen)?;Ok(Expr::Call(n,a))}else{Ok(Expr::Var(n))}},Token::LParen=>{let x=self.expr()?;self.eat(Token::RParen)?;Ok(x)},x=>Err(format!("unexpected token {:?}",x))}}
}

#[derive(Debug,Clone,PartialEq)] enum Value { Int(i64), Str(String), Bool(bool), Unit, Thread(usize) }
struct Vm { funcs:HashMap<String,Function> }
impl Vm { fn run(&self)->Result<Value,String>{self.call("main",vec![])} fn call(&self,n:&str,args:Vec<Value>)->Result<Value,String>{if n=="print"{for x in args{println!("{}",show(&x))}return Ok(Value::Unit)}let f=self.funcs.get(n).ok_or_else(||format!("unknown function `{n}`"))?;let mut e=HashMap::new();for(i,p)in f.params.iter().enumerate(){e.insert(p.clone(),args.get(i).cloned().unwrap_or(Value::Unit));}match exec(&f.body,&mut e,self)?{Some(v)=>Ok(v),None=>Ok(Value::Unit)}}}
fn show(v:&Value)->String{match v{Value::Int(x)=>x.to_string(),Value::Str(x)=>x.clone(),Value::Bool(x)=>x.to_string(),Value::Unit=>"unit".into(),Value::Thread(id)=>format!("thread({id})")}}
fn truth(v:&Value)->bool{matches!(v,Value::Bool(true))||matches!(v,Value::Int(x)if *x!=0)}
fn val(x:&Expr,e:&mut HashMap<String,Value>,vm:&Vm)->Result<Value,String>{match x{Expr::Int(x)=>Ok(Value::Int(*x)),Expr::Str(x)=>Ok(Value::Str(x.clone())),Expr::Bool(x)=>Ok(Value::Bool(*x)),Expr::Var(n)=>e.get(n).cloned().ok_or_else(||format!("undefined variable `{n}`")),Expr::Call(n,a)=>{let z=a.iter().map(|x|val(x,e,vm)).collect::<Result<Vec<_>,_>>()?;vm.call(n,z)},Expr::Binary(a,o,b)=>{let x=val(a,e,vm)?;let y=val(b,e,vm)?;bin(x,o,y)}}}
fn bin(a:Value,o:&Token,b:Value)->Result<Value,String>{match (a,b,o){(Value::Int(x),Value::Int(y),Token::Plus)=>Ok(Value::Int(x+y)),(Value::Int(x),Value::Int(y),Token::Minus)=>Ok(Value::Int(x-y)),(Value::Int(x),Value::Int(y),Token::Star)=>Ok(Value::Int(x*y)),(Value::Int(x),Value::Int(y),Token::Slash)=>Ok(Value::Int(x/y)),(Value::Int(x),Value::Int(y),Token::EqEq)=>Ok(Value::Bool(x==y)),(Value::Int(x),Value::Int(y),Token::BangEq)=>Ok(Value::Bool(x!=y)),(Value::Int(x),Value::Int(y),Token::Lt)=>Ok(Value::Bool(x<y)),(Value::Int(x),Value::Int(y),Token::Lte)=>Ok(Value::Bool(x<=y)),(Value::Int(x),Value::Int(y),Token::Gt)=>Ok(Value::Bool(x>y)),(Value::Int(x),Value::Int(y),Token::Gte)=>Ok(Value::Bool(x>=y)),(Value::Str(x),Value::Str(y),Token::Plus)=>Ok(Value::Str(x+&y)),(x,y,Token::EqEq)=>Ok(Value::Bool(x==y)),(x,y,Token::BangEq)=>Ok(Value::Bool(x!=y)),_=>Err("invalid operands".into())}}
fn exec_scoped(xs:&[Stmt],e:&mut HashMap<String,Value>,vm:&Vm)->Result<Option<Value>,String>{let keys:Vec<String>=e.keys().cloned().collect();let shadowed:Vec<String>=xs.iter().filter_map(|s|if let Stmt::Let(n,_)=s{Some(n.clone())}else{None}).collect();let mut inner=e.clone();let result=exec(xs,&mut inner,vm);for k in keys{if !shadowed.contains(&k){if let Some(v)=inner.get(&k){e.insert(k,v.clone());}}}result}
fn exec(xs:&[Stmt],e:&mut HashMap<String,Value>,vm:&Vm)->Result<Option<Value>,String>{for s in xs{match s{Stmt::Let(n,x)|Stmt::Assign(n,x)=>{let value=val(x,e,vm)?;e.insert(n.clone(),value);},Stmt::Decl(n,_)=>{e.insert(n.clone(),Value::Unit);},Stmt::Expr(x)=>{val(x,e,vm)?;},Stmt::Return(x)=>return Ok(Some(val(x,e,vm)?)),Stmt::If(c,a,b)=>{if truth(&val(c,e,vm)?){if let Some(v)=exec_scoped(a,e,vm)?{return Ok(Some(v))}}else if let Some(v)=exec_scoped(b,e,vm)?{return Ok(Some(v))}},Stmt::While(c,b)=>{while truth(&val(c,e,vm)?){if let Some(v)=exec_scoped(b,e,vm)?{return Ok(Some(v))}}}}}Ok(None)}
fn type_name(t:&Type)->&'static str{match t{Type::Int=>"Int",Type::Str=>"String",Type::Bool=>"Bool",Type::Unit=>"Unit",Type::Ref(_)=>"&reference",Type::MutRef(_)=>"&mut reference",Type::Unknown=>"Unknown"}}
fn expr_type(x:&Expr,env:&HashMap<String,Type>,sigs:&HashMap<String,(Vec<Type>,Type)>)->Result<Type,String>{match x{Expr::Int(_)=>Ok(Type::Int),Expr::Str(_)=>Ok(Type::Str),Expr::Bool(_)=>Ok(Type::Bool),Expr::Var(n)=>env.get(n).cloned().ok_or_else(||format!("undefined variable `{n}`")),Expr::Call(n,args)=>{if n=="print"||n=="spawn"||n=="join"{for a in args{expr_type(a,env,sigs)?;}return Ok(if n=="spawn"{Type::Unknown}else{Type::Unit})}let (params,ret)=sigs.get(n).ok_or_else(||format!("unknown function `{n}`"))?;if args.len()!=params.len(){return Err(format!("function `{n}` expects {} argument(s), got {}",params.len(),args.len()))}for(i,a)in args.iter().enumerate(){let got=expr_type(a,env,sigs)?;let compatible=match &params[i]{Type::Ref(inner)|Type::MutRef(inner)=>got==**inner,_=>got==params[i]};if !compatible{return Err(format!("function `{n}` argument {} expects {}, got {}",i+1,type_name(&params[i]),type_name(&got)))}}Ok(ret.clone())},Expr::Binary(a,o,b)=>{let ta=expr_type(a,env,sigs)?;let tb=expr_type(b,env,sigs)?;match o{Token::Plus=>if ta==tb&&(ta==Type::Int||ta==Type::Str){Ok(ta)}else{Err(format!("operator + expects two Int values or two String values, got {} and {}",type_name(&ta),type_name(&tb)))},Token::Minus|Token::Star|Token::Slash=>if ta==Type::Int&&tb==Type::Int{Ok(Type::Int)}else{Err(format!("arithmetic operator expects Int, got {} and {}",type_name(&ta),type_name(&tb)))},Token::EqEq|Token::BangEq=>if ta==tb{Ok(Type::Bool)}else{Err(format!("comparison requires matching types, got {} and {}",type_name(&ta),type_name(&tb)))},Token::Lt|Token::Lte|Token::Gt|Token::Gte=>if ta==Type::Int&&tb==Type::Int{Ok(Type::Bool)}else{Err("ordering comparison expects Int values".into())},_=>Err("invalid operator".into())}}}}
fn check_typed_stmts(xs:&[Stmt],env:&mut HashMap<String,Type>,sigs:&HashMap<String,(Vec<Type>,Type)>,ret:&Type)->Result<(),String>{for s in xs{match s{Stmt::Let(n,x)=>{let t=expr_type(x,env,sigs)?;env.insert(n.clone(),t);},Stmt::Decl(n,t)=>{env.insert(n.clone(),t.clone());},Stmt::Assign(n,x)=>{let got=expr_type(x,env,sigs)?;let old=env.get(n).ok_or_else(||format!("assignment to undefined variable `{n}`"))?;if *old!=got{return Err(format!("cannot assign {} to `{n}` of type {}",type_name(&got),type_name(old))) }},Stmt::Expr(x)=>{expr_type(x,env,sigs)?;},Stmt::Return(x)=>{let got=expr_type(x,env,sigs)?;if *ret!=Type::Unit&&got!=*ret{return Err(format!("return type mismatch: expected {}, got {}",type_name(ret),type_name(&got))) }},Stmt::If(c,a,b)=>{if expr_type(c,env,sigs)?!=Type::Bool{return Err("if condition must be Bool".into())}check_typed_stmts(a,&mut env.clone(),sigs,ret)?;check_typed_stmts(b,&mut env.clone(),sigs,ret)?;},Stmt::While(c,b)=>{if expr_type(c,env,sigs)?!=Type::Bool{return Err("while condition must be Bool".into())}check_typed_stmts(b,&mut env.clone(),sigs,ret)?;}}}Ok(())}
fn copyable(t:&Type)->bool{matches!(t,Type::Int|Type::Bool|Type::Unit|Type::Ref(_)|Type::MutRef(_))}
fn moved_var(x:&Expr)->Option<String>{if let Expr::Var(n)=x{Some(n.clone())}else{None}}
fn ownership_expr(x:&Expr,env:&HashMap<String,Type>,moved:&mut HashMap<String,bool>,move_value:bool,sigs:&HashMap<String,(Vec<Type>,Type)>)->Result<(),String>{match x{Expr::Var(n)=>{if *moved.get(n).unwrap_or(&false){return Err(format!("use of moved value `{n}`; use `.clone()` before moving it again"))}if move_value&&!copyable(env.get(n).unwrap_or(&Type::Unknown)){moved.insert(n.clone(),true);}},Expr::Binary(a,_,b)=>{ownership_expr(a,env,moved,false,sigs)?;ownership_expr(b,env,moved,false,sigs)?},Expr::Call(n,args)=>{for a in args{let borrow=if n=="print"||n=="spawn"{true}else{sigs.get(n).and_then(|(ps,_)|ps.first()).map(|t|matches!(t,Type::Ref(_)|Type::MutRef(_))).unwrap_or(false)};ownership_expr(a,env,moved,!borrow,sigs)?;}},_=>{}}Ok(())}
fn ownership_stmts(xs:&[Stmt],env:&mut HashMap<String,Type>,moved:&mut HashMap<String,bool>,sigs:&HashMap<String,(Vec<Type>,Type)>)->Result<(),String>{for s in xs{match s{Stmt::Let(n,x)=>{ownership_expr(x,env,moved,moved_var(x).is_some(),sigs)?;let t=expr_type(x,env,&HashMap::new()).unwrap_or(Type::Unknown);env.insert(n.clone(),t);moved.insert(n.clone(),false);},Stmt::Assign(n,x)=>{ownership_expr(x,env,moved,moved_var(x).is_some(),sigs)?;if !env.contains_key(n){return Err(format!("assignment to undefined variable `{n}`"))}moved.insert(n.clone(),false);},Stmt::Decl(n,t)=>{env.insert(n.clone(),t.clone());moved.insert(n.clone(),false);},Stmt::Expr(x)|Stmt::Return(x)=>ownership_expr(x,env,moved,false,sigs)?,Stmt::If(c,a,b)=>{ownership_expr(c,env,moved,false,sigs)?;ownership_stmts(a,env,moved,sigs)?;ownership_stmts(b,env,moved,sigs)?;},Stmt::While(c,b)=>{ownership_expr(c,env,moved,false,sigs)?;ownership_stmts(b,env,moved,sigs)?;}}}Ok(())}
fn definite_expr(x:&Expr,types:&HashMap<String,Type>,assigned:&HashMap<String,()>)->Result<(),String>{match x{Expr::Var(n)=>{if !types.contains_key(n){return Err(format!("undefined variable `{n}`"))}if !assigned.contains_key(n){return Err(format!("use of uninitialized variable `{n}`"))}},Expr::Binary(a,_,b)=>{definite_expr(a,types,assigned)?;definite_expr(b,types,assigned)?},Expr::Call(_,args)=>for a in args{definite_expr(a,types,assigned)?},_=>{}}Ok(())}
fn intersect(a:&HashMap<String,()>,b:&HashMap<String,()>)->HashMap<String,()>{a.iter().filter(|(k,_)|b.contains_key(*k)).map(|(k,v)|(k.clone(),*v)).collect()}
fn definite_stmts(xs:&[Stmt],types:&mut HashMap<String,Type>,assigned:&mut HashMap<String,()>)->Result<(),String>{for s in xs{match s{Stmt::Decl(n,t)=>{types.insert(n.clone(),t.clone());assigned.remove(n);},Stmt::Let(n,x)=>{definite_expr(x,types,assigned)?;types.insert(n.clone(),expr_type(x,types,&HashMap::new()).unwrap_or(Type::Unknown));assigned.insert(n.clone(),());},Stmt::Assign(n,x)=>{if !types.contains_key(n){return Err(format!("assignment to undefined variable `{n}`"))}definite_expr(x,types,assigned)?;assigned.insert(n.clone(),());},Stmt::Expr(x)|Stmt::Return(x)=>definite_expr(x,types,assigned)?,Stmt::If(c,a,b)=>{definite_expr(c,types,assigned)?;let mut at=assigned.clone();let mut bt=assigned.clone();definite_stmts(a,types,&mut at)?;definite_stmts(b,types,&mut bt)?;*assigned=intersect(&at,&bt);},Stmt::While(c,b)=>{definite_expr(c,types,assigned)?;let mut body=assigned.clone();definite_stmts(b,types,&mut body)?;}}}Ok(())}
fn check_program(fs:&[Function])->Result<(),String>{let mut names=HashMap::new();let mut sigs=HashMap::new();for f in fs{if names.insert(f.name.clone(),()).is_some(){return Err(format!("duplicate function `{}`",f.name))}sigs.insert(f.name.clone(),(f.param_types.clone(),f.return_type.clone()));}if !names.contains_key("main"){return Err("program must define fn main()".into())}for f in fs{let mut env=HashMap::new();for(i,n)in f.params.iter().enumerate(){env.insert(n.clone(),f.param_types.get(i).cloned().unwrap_or(Type::Unknown));}check_typed_stmts(&f.body,&mut env,&sigs,&f.return_type)?;let mut definite=HashMap::new();for(i,n)in f.params.iter().enumerate(){definite.insert(n.clone(),f.param_types.get(i).cloned().unwrap_or(Type::Unknown));}let mut assigned=HashMap::new();for n in &f.params{assigned.insert(n.clone(),());}definite_stmts(&f.body,&mut definite,&mut assigned)?;let mut moved=HashMap::new();ownership_stmts(&f.body,&mut env,&mut moved,&sigs)?;}Ok(())}
fn check_stmts(xs:&[Stmt],names:&HashMap<String,()>)->Result<(),String>{for s in xs{match s{Stmt::Decl(_,_)=>{},Stmt::Expr(x)|Stmt::Let(_,x)|Stmt::Assign(_,x)|Stmt::Return(x)=>check_expr(x,names)?,Stmt::If(c,a,b)=>{check_expr(c,names)?;check_stmts(a,names)?;check_stmts(b,names)?},Stmt::While(c,b)=>{check_expr(c,names)?;check_stmts(b,names)?}}}Ok(())}
fn check_expr(x:&Expr,names:&HashMap<String,()>)->Result<(),String>{match x{Expr::Binary(a,_,b)=>{check_expr(a,names)?;check_expr(b,names)?},Expr::Call(n,a)=>{if n!="print"&&!names.contains_key(n){return Err(format!("unknown function `{n}`"))}for x in a{check_expr(x,names)?}},_=>{}}Ok(())}
#[derive(Debug,Clone)] enum Op { Const(Value), Load(String), Store(String), Add, Sub, Mul, Div, Eq, Ne, Lt, Lte, Gt, Gte, Call(String,usize), Print, Pop, JumpIfFalse(usize), Jump(usize), Return, Halt }
#[derive(Debug,Clone)] struct Chunk { code:Vec<Op> }
fn compile_expr(x:&Expr,c:&mut Chunk)->Result<(),String>{match x{Expr::Int(v)=>c.code.push(Op::Const(Value::Int(*v))),Expr::Str(v)=>c.code.push(Op::Const(Value::Str(v.clone()))),Expr::Bool(v)=>c.code.push(Op::Const(Value::Bool(*v))),Expr::Var(n)=>c.code.push(Op::Load(n.clone())),Expr::Binary(a,o,b)=>{compile_expr(a,c)?;compile_expr(b,c)?;c.code.push(match o{Token::Plus=>Op::Add,Token::Minus=>Op::Sub,Token::Star=>Op::Mul,Token::Slash=>Op::Div,Token::EqEq=>Op::Eq,Token::BangEq=>Op::Ne,Token::Lt=>Op::Lt,Token::Lte=>Op::Lte,Token::Gt=>Op::Gt,Token::Gte=>Op::Gte,_=>return Err("invalid bytecode operator".into())})},Expr::Call(n,a)=>{for x in a{compile_expr(x,c)?}c.code.push(if n=="print"{Op::Print}else{Op::Call(n.clone(),a.len())})}}Ok(())}
fn compile_stmts(xs:&[Stmt],c:&mut Chunk)->Result<(),String>{for s in xs{match s{Stmt::Let(n,x)|Stmt::Assign(n,x)=>{compile_expr(x,c)?;c.code.push(Op::Store(n.clone()));},Stmt::Decl(_,_)=>{},Stmt::Expr(x)=>{compile_expr(x,c)?;c.code.push(Op::Pop);},Stmt::Return(x)=>{compile_expr(x,c)?;c.code.push(Op::Return);},Stmt::If(cond,a,b)=>{compile_expr(cond,c)?;let jf=c.code.len();c.code.push(Op::JumpIfFalse(0));compile_stmts(a,c)?;let j=c.code.len();c.code.push(Op::Jump(0));let else_ip=c.code.len();compile_stmts(b,c)?;let end=c.code.len();c.code[jf]=Op::JumpIfFalse(else_ip);c.code[j]=Op::Jump(end);},Stmt::While(cond,b)=>{let start=c.code.len();compile_expr(cond,c)?;let jf=c.code.len();c.code.push(Op::JumpIfFalse(0));compile_stmts(b,c)?;c.code.push(Op::Jump(start));let end=c.code.len();c.code[jf]=Op::JumpIfFalse(end);}}}Ok(())}
fn compile_functions(fs:&[Function])->Result<HashMap<String,(Vec<String>,Chunk)>,String>{let mut out=HashMap::new();for f in fs{let mut c=Chunk{code:Vec::new()};compile_stmts(&f.body,&mut c)?;c.code.push(Op::Const(Value::Unit));c.code.push(Op::Return);out.insert(f.name.clone(),(f.params.clone(),c));}Ok(out)}
struct BytecodeVm{funcs:HashMap<String,(Vec<String>,Chunk)>}
impl BytecodeVm{fn call(&self,n:&str,args:Vec<Value>)->Result<Value,String>{if n=="print"{for v in args{println!("{}",show(&v))}return Ok(Value::Unit)}if n=="spawn"{let target=match args.first(){Some(Value::Str(s))=>s.clone(),_=>return Err("spawn expects a function name string".into())};let funcs=self.funcs.clone();let id=NEXT_THREAD_ID.fetch_add(1,Ordering::Relaxed);let handle=thread::spawn(move||BytecodeVm{funcs}.call(&target,vec![]).unwrap_or(Value::Unit));thread_table().lock().unwrap().insert(id,handle);return Ok(Value::Thread(id))}if n=="join"{let id=match args.first(){Some(Value::Thread(i))=>*i,_=>return Err("join expects a thread handle".into())};let handle=thread_table().lock().unwrap().remove(&id).ok_or("unknown thread handle")?;return handle.join().map_err(|_|"thread panicked".into())}let(fparams,chunk)=self.funcs.get(n).ok_or_else(||format!("unknown function `{n}`"))?.clone();let mut locals=HashMap::new();for(i,p)in fparams.iter().enumerate(){locals.insert(p.clone(),args.get(i).cloned().unwrap_or(Value::Unit));}let mut stack=Vec::new();let mut ip=0;while ip<chunk.code.len(){match &chunk.code[ip]{Op::Const(v)=>stack.push(v.clone()),Op::Load(n)=>stack.push(locals.get(n).cloned().ok_or_else(||format!("undefined variable `{n}`"))?),Op::Store(n)=>{let v=stack.pop().ok_or("stack underflow")?;locals.insert(n.clone(),v);},Op::Add|Op::Sub|Op::Mul|Op::Div|Op::Eq|Op::Ne|Op::Lt|Op::Lte|Op::Gt|Op::Gte=>{let b=stack.pop().ok_or("stack underflow")?;let a=stack.pop().ok_or("stack underflow")?;let op=match &chunk.code[ip]{Op::Add=>Token::Plus,Op::Sub=>Token::Minus,Op::Mul=>Token::Star,Op::Div=>Token::Slash,Op::Eq=>Token::EqEq,Op::Ne=>Token::BangEq,Op::Lt=>Token::Lt,Op::Lte=>Token::Lte,Op::Gt=>Token::Gt,Op::Gte=>Token::Gte,_=>unreachable!()};stack.push(bin(a,&op,b)?);},Op::Call(n,c)=>{let mut a=Vec::new();for _ in 0..*c{a.push(stack.pop().ok_or("stack underflow")?)}a.reverse();stack.push(self.call(n,a)?);},Op::Print=>{let v=stack.pop().ok_or("stack underflow")?;println!("{}",show(&v));stack.push(Value::Unit);},Op::Pop=>{stack.pop();},Op::JumpIfFalse(to)=>{let v=stack.pop().ok_or("stack underflow")?;if !truth(&v){ip=*to;continue}},Op::Jump(to)=>{ip=*to;continue},Op::Return=>return Ok(stack.pop().unwrap_or(Value::Unit)),Op::Halt=>return Ok(Value::Unit)}ip+=1}Ok(Value::Unit)}}
fn execute(src:&str)->Result<Value,String>{let toks=lex(src)?;let mut p=Parser::new(toks);let fs=p.program()?;check_program(&fs)?;let funcs=compile_functions(&fs)?;BytecodeVm{funcs}.call("main",vec![])}
fn diagnostic(src:&str,error:&str)->String{let needle=error.split('`').nth(1);let mut line_no=1;let mut line_text="";for(i,line)in src.lines().enumerate(){if needle.map(|n|line.contains(n)).unwrap_or(false){line_no=i+1;line_text=line;break}if line_text.is_empty(){line_text=line;}}format!("error: {error}\n  --> source.snp:{line_no}:1\n   |\n{:>3} | {}\n   | ^",line_no,line_text)}
fn main(){let a:Vec<String>=env::args().collect();if a.len()<2{eprintln!("S+N++ v0.1 — usage: snp run <file.snp> | snp check <file.snp> | snp repl");return}if a[1]=="repl"{let mut line=String::new();loop{print!("snp> ");io::stdout().flush().unwrap();line.clear();if io::stdin().read_line(&mut line).unwrap()==0{break}let src=format!("fn main() {{{}}}",line);match execute(&src){Ok(v)=>if v!=Value::Unit{println!("{}",show(&v))},Err(e)=>eprintln!("{}",diagnostic(&src,&e))}}return}if a.len()<3{eprintln!("missing file");return}let src=match fs::read_to_string(&a[2]){Ok(x)=>x,Err(e)=>{eprintln!("cannot read file: {e}");return}};match execute(&src){Ok(v)=>{if a[1]=="check"{println!("ok: valid S+N++ program")}else if v!=Value::Unit{println!("program returned {}",show(&v))}},Err(e)=>eprintln!("{}",diagnostic(&src,&e))}}

#[cfg(test)] mod tests {use super::*;#[test]fn arithmetic(){let s="fn main(){ print(2+3*4); return 0; }";assert_eq!(execute(s),Ok(Value::Int(0)));}#[test]fn function_call(){let s="fn add(a:Int,b:Int){return a+b;} fn main(){return add(2,3);}";assert_eq!(execute(s),Ok(Value::Int(5)));}#[test]fn unknown_function_is_diagnostic(){let s="fn main(){missing();}";assert!(execute(s).unwrap_err().contains("unknown function"));}#[test]fn type_mismatch_is_diagnostic(){let s="fn add(a:Int,b:Int)->Int{return a+b;} fn main()->Int{return add(2,\"x\");}";assert!(execute(s).unwrap_err().contains("expects Int"));}#[test]fn condition_must_be_bool(){let s="fn main(){if 1 { print(1); }}";assert!(execute(s).unwrap_err().contains("condition must be Bool"));}#[test]fn string_move_is_tracked(){let s="fn consume(x:String){print(x);} fn main(){let a=\"hello\"; consume(a); print(a);}";assert!(execute(s).unwrap_err().contains("use of moved value"));}#[test]fn immutable_borrow_preserves_owner(){let s="fn view(x:&String){print(x);} fn main(){let a=\"hello\"; view(a); print(a);}";assert_eq!(execute(s),Ok(Value::Unit));}#[test]fn mutable_reference_syntax_is_valid(){let s="fn update(x:&mut String){print(x);} fn main(){let a=\"hello\"; update(a); print(a);}";assert_eq!(execute(s),Ok(Value::Unit));}#[test]fn spawn_and_join_run_worker(){let s="fn worker(){print(\"worker\");} fn main(){let t=spawn(\"worker\"); join(t);}";assert_eq!(execute(s),Ok(Value::Unit));}#[test]fn multiple_workers_can_join(){let s="fn worker(){return 7;} fn main(){let a=spawn(\"worker\"); let b=spawn(\"worker\"); join(a); join(b);}";assert_eq!(execute(s),Ok(Value::Unit));}#[test]fn function_locals_do_not_leak(){let s="fn helper(){let secret=1;} fn main(){print(secret);}";assert!(execute(s).unwrap_err().contains("undefined variable"));}#[test]fn assignment_requires_existing_variable(){let s="fn main(){missing=1;}";assert!(execute(s).unwrap_err().contains("undefined variable"));}#[test]fn lexical_shadowing_keeps_outer_value(){let s="fn main(){let x=1; if true {let x=2; print(x);} print(x);}";assert_eq!(execute(s),Ok(Value::Unit));}#[test]fn branch_must_definitely_assign(){let s="fn main(){let x:Int; if true {x=1;} print(x);}";assert!(execute(s).unwrap_err().contains("uninitialized variable"));}#[test]fn both_branches_assign_value(){let s="fn main(){let x:Int; if true {x=1;} else {x=2;} print(x);}";assert_eq!(execute(s),Ok(Value::Unit));}#[test]fn loop_assignment_is_not_definite_after_loop(){let s="fn main(){let x:Int; while false {x=1;} print(x);}";assert!(execute(s).unwrap_err().contains("uninitialized variable"));}}
